exclude = [
    ".venv",
    "pyproject.toml",
    ".git",
]
line-length = 88
indent-width = 4
target-version = "py311"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"